### PR TITLE
Add capacity to automatically detect the module to use depending on the position

### PR DESCRIPTION
**Pull request by javiersanp**
Hello.

As commented, I tried to guess the country with a query to Nominatim. These are the changes:
PointInfoPreference adds a checkbox to select "Auto mode".
AbstractPointInfoModule adds a method to return the name of the area this module is valid.
ReverseFinder to query Nominatim for the address of a given position.
ReverseRecord to holds the results of the previous query.
PointInfoUtils.getModule returns the module for the area detected if auto mode is on or the selected in the preferences if else.

### CODE REVIEW

**Comment by mkyral** [comment]
Hi,
sorry for delay caused by very nice spring weather ;-) Updated plugin was already published.

I made one change - the Auto mode is off by default - could be changed in future.

Regards,
Marián

**Comment by javiersanp** [comment]
Great.
Willing to see it in the stable josm version.

**Comment by javiersanp** [comment]
Hello @mkyral 
The plugging is taking a lot to update in https://svn.openstreetmap.org/applications/editors/josm/dist/pointInfo.jar
Do you know if this is normal and how long can it take?
Cheers, Javier

**Comment by mkyral** [comment]
Grrr.
I just checked the log and there is some issue with the new version commit :-(
Probably something changed or I forgot about something. I have to check. Will try this afternoon.

```
Updating '.':
At revision 34168.
svn: E155007: None of the targets are working copies
Skipped '../dist/home/marian/projekty/josm/josm_plugins/dist/pointInfo.jar'
Skipped '../dist/home/marian/projekty/josm/josm_plugins/dist/pointInfo-javadoc.jar'
Skipped '../dist/home/marian/projekty/josm/josm_plugins/dist/pointInfo-sources.jar'
svn: E200009: Commit failed (details follow):
svn: E200009: '/home/marian/projekty/josm/josm_plugins/dist/pointInfo-sources.jar' is not under version control
```

**Comment by mkyral** [comment]
@javiersanp I hope it will OK now. 

```
Sending        pointInfo.jar
Transmitting file data .done
Committing transaction...
Committed revision 34195.
```

**Comment by javiersanp** [comment]
Yes, working. Wonderful!
Thank you

**Pull request merged**
